spring.application.name=ai-agent
spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.name=sesame-ai-agent
spring.ai.mcp.client.version=0.0.1
spring.ai.mcp.client.request-timeout=30s

sesame.ai-agent.tool-names.simulation-launch=runSimulation
